id: I3B537376
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:51:50+00:00'
last_modified: '2022-06-07T13:56:53.020080+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG20858
  title: ཆབ་སྲིད་དཔལ་འབྱོར་རིག་པའི་མིང་ཚིག་གི་འགྲེལ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C7D0:
      image_group_id: I1KG20911
      title: ''
      total_pages: 418
      order: 1
      base_file: C7D0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
